// Source of truth: Juliette's live Gamma deck "The Unspoken Distance"
// (g_ko86mkctllxkw18), read in full (all 21 sections, ~114,663 characters)
// and transcribed verbatim: every paragraph, every THE PRACTICE box, every
// EMBODIMENT EXERCISE box, every HOW THIS PATTERN WILL SHOW UP box, every
// bold/accent line, every closing "You stop being the man who X. You become
// the man who Y." blockquote. Nothing summarised, nothing dropped, nothing
// paraphrased into different words, per Juliette 31 Jul 2026: the app must
// carry the SAME depth as the £77 paid guide, nothing thinned out.
//
// The deck's own H1 typo "The Intimacy and communicaton Cards" is corrected
// to "Communication" here (a real typo, not a stylistic choice, per spec).
// A handful of other obvious markup/grammar glitches in the raw export
// ("It important", a stray "<" character) are silently corrected the same
// way; no wording, claim, or mechanic was changed or added.
//
// One addition beyond the deck: "The Groundedness Practice" entry carries
// Juliette's real Vimeo embodiment video (vimeoId 1208083538), placed after
// The Grounding Practice section. The 2-4 sentence blurb framing it as a
// weekly return practice is new copy, written to voice-core.md + canon.md
// (31 Jul 2026); everything else in this file is deck transcription.
//
// Images are the real photography from the deck, downloaded into
// /public/unspoken-distance so the app doesn't depend on Gamma's CDN
// staying up. 25 real photos were found and downloaded; the generic
// AI-illustration <diagram> elements and pictographic.ai icon SVGs
// throughout the deck were skipped as decorative, not content.

import { ContentBlock } from "./blocks";
import { PracticeEntry, PracticeCollection } from "./ten-touch-rituals";

export const theUnspokenDistance: PracticeCollection = {
  slug: "the-unspoken-distance",
  title: "The Unspoken Distance",
  subtitle: "A guide for men who love women they can no longer reach",
  byline: "By Juliette Karaman",
  heroImage: "/unspoken-distance/hero-couple-bar.jpeg",
  unlockMode: "free-browse",
  entries: [
    // ------------------------------------------------------------- intro
    {
      slug: "before-you-read-this",
      order: 0,
      title: "Before You Read This",
      kind: "essay",
      image: "/unspoken-distance/hero-couple-bar.jpeg",
      imageAlt: "A couple sitting closely together, dressed elegantly, at a bar",
      imageSide: "left",
      body: [
        { kind: "p", text: "This is written to the man whose partner has gone quiet. That is the primary voice." },
        { kind: "p", text: "It lands for anyone else who recognises the pattern inside themselves." },
        { kind: "p", text: "If you are out of a relationship and trying to understand what happened, this still applies." },
        { kind: "p", text: "If you are dating and cannot quite get close, you can learn to read this before you walk into the next one." },
        { kind: "p", text: "If you are the one who has been going quiet, you will see your own closing mapped here. Same material. Different chair." },
        { kind: "p", text: "The body does not ask who is reading. It speaks to whoever is listening.", emphasis: "accent" },
        { kind: "p", text: "— Juliette" },
      ],
    },
    {
      slug: "her-withdrawal-is-not-a-verdict-on-you",
      order: 1,
      title: "Her Withdrawal Is Not a Verdict on You.",
      eyebrow: "Before We Begin",
      kind: "essay",
      image: "/unspoken-distance/couple-close-portrait.jpg",
      imageAlt: "A close, quiet portrait of a couple",
      imageSide: "right",
      body: [
        { kind: "p", text: "Read that again if you need to.", emphasis: "bold" },
        { kind: "p", text: "You already know something is wrong. You don't need this guide to tell you that." },
        { kind: "p", text: "What you may not know is what's actually happening. Inside her. In her body. In the part of her that has nothing to do with how much she loves you." },
        { kind: "p", text: "This is not a guide about fixing yourself or winning her back." },
        { kind: "p", text: "It's a translation.", emphasis: "bold" },
        { kind: "p", text: "Of what her body is doing, and why. Of what the distance actually is, and where it lives." },
        { kind: "p", text: "Once you understand that, you stop taking it personally. Once you stop taking it personally, something in the room shifts. She feels that shift before she can name it." },
        { kind: "p", text: "That's where this begins.", emphasis: "bold" },
        { kind: "quote", text: "What This Guide Is" },
        { kind: "p", text: "Over 27 years I have worked with women, men, and couples at the point where intimacy has gone quiet." },
        { kind: "p", text: "I have worked with more than 650 couples. I have worked with women carrying 20 years of body-held experience that released in a single session." },
        { kind: "p", text: "I have worked with the couple who had not touched each other in 23 years and watched them leave for their second honeymoon." },
        { kind: "p", text: "I started this work with children who felt everything and couldn't translate it into something the world around them could receive." },
        { kind: "p", text: "That is still the work. The people are different. The tools have multiplied." },
        { kind: "p", text: "The work has never changed." },
        { kind: "p", text: "Twenty-seven years of practice. Over 650 couples. 980 women, held, heard, and helped back into their own bodies.", emphasis: "bold" },
        { kind: "p", text: "What I want to give you in this guide is not a technique. It's a way of seeing." },
        { kind: "p", text: "When you see what is actually happening in her body, you stop trying to fix the wrong thing.", emphasis: "accent" },
        { kind: "quote", text: "What This Guide Is Not" },
        { kind: "p", text: "It is not a manual for getting her to want you again. It is not a list of things to say or do. It is not a guarantee." },
        { kind: "p", text: "If you read it and something opens in you, that is the point." },
        { kind: "big", text: "Ready? Let's go in." },
        { kind: "image", src: "/unspoken-distance/feet-on-the-floor.jpg", alt: "Bare feet on an old wooden floor" },
        { kind: "p", text: "Before you read further — put both feet flat on the floor.", emphasis: "accent" },
        { kind: "p", text: "Take one full breath. Arrive in this moment.", emphasis: "accent" },
        { kind: "p", text: "This guide works differently when your body is here for it.", emphasis: "accent" },
      ],
    },
    {
      slug: "what-she-actually-needs",
      order: 2,
      title: "What She Actually Needs",
      eyebrow: "Part One",
      kind: "essay",
      image: "/unspoken-distance/transmitting-on-one-channel.jpeg",
      imageAlt: "A quiet, ordinary moment between two people",
      imageSide: "left",
      body: [
        { kind: "p", text: "You have been giving her what you thought she needed. Stability. Security. Presence. Your best effort at being a good husband, a good father, a good man." },
        { kind: "p", text: "Still something is missing." },
        { kind: "p", text: "This is not a failure of effort. It is a mismatch of frequency." },
        { kind: "p", text: "You have been transmitting on one channel.", emphasis: "bold" },
        { kind: "p", text: "She has been waiting on another.", emphasis: "bold" },
      ],
    },
    {
      slug: "to-feel-safe-before-she-can-open",
      order: 3,
      title: "To Feel Safe Before She Can Open",
      kind: "essay",
      image: "/unspoken-distance/hero-couple-bar.jpeg",
      imageAlt: "A couple close together, at ease",
      imageSide: "right",
      body: [
        { kind: "p", text: "Everything else depends on this one." },
        { kind: "p", text: "Safety is not comfort.", emphasis: "bold" },
        { kind: "p", text: "It is not the absence of difficulty.", emphasis: "bold" },
        { kind: "p", text: "It is the felt sense that she can be exactly where she is: uncertain, emotional, tired, wanting, afraid," },
        { kind: "p", text: "and nothing will go wrong.", emphasis: "bold" },
        { kind: "p", text: "When her body feels safe her muscles soften. Her breath drops. The part of her that is always slightly on guard goes quiet." },
        { kind: "p", text: "That quieting cannot be demanded." },
        { kind: "p", text: "It cannot be rushed. It arrives when the conditions are right." },
        { kind: "p", text: "You are one of those conditions." },
        { kind: "p", text: "Not what you say." },
        { kind: "p", text: "Not what you do." },
        { kind: "p", text: "The quality of how you are in the room with her.", emphasis: "bold" },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Tonight, sit near her." },
            { text: "Not with a question. Not with a plan. Not with anything you want from the interaction." },
            { text: "Just be in the room, present, with nothing attached." },
            { text: "Notice what happens in your body when you don't have an agenda." },
            { text: "Let all of that be there." },
            { text: "Don't act on any of it. Just sit." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Before you sit near her, pause at the door of the room." },
            { text: "Take one full breath. Not a performance of breathing: an actual breath in through the nose, slow exhale out." },
            { text: "Notice where that breath settles in your body." },
            { text: "Does your chest drop slightly? Does something in your belly release? Or does the tightness stay?" },
            { text: "Whatever is there, let it be there. You are not trying to manufacture calm. You are just noticing what you are carrying before you enter the room." },
            { text: "If there is an outcome underneath the breath: a hope, a need, a wish for her to notice you differently tonight, feel the weight of that." },
            { text: "Just for a second. Then let it move down through your feet into the floor." },
            { text: "Now walk in." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll do this for two evenings and then on the third, you'll sit near her and start tracking her response.",
            "You'll look for a sign that it's working.",
            "The moment you track her response, the agenda is back.",
            "She'll feel the shift before you realise you made it.",
            "The practice is not about getting a result. The practice is the result.",
          ],
        },
        { kind: "p", text: "You stop being the man who tries to make her feel safe.", emphasis: "accent" },
        { kind: "p", text: "You become the man whose presence is the safety.", emphasis: "accent" },
      ],
    },
    {
      slug: "to-be-seen-beyond-her-roles",
      order: 4,
      title: "To Be Seen Beyond Her Roles",
      kind: "essay",
      image: "/unspoken-distance/couple-close-portrait.jpg",
      imageAlt: "A close, quiet portrait of a couple",
      imageSide: "left",
      body: [
        { kind: "p", text: "She is a mother, maybe. A wife, a partner, a lover. A manager of the household. A keeper of the schedule. She does it well and she does it quietly and almost nobody notices." },
        { kind: "p", text: "What she wants is not gratitude for the tasks." },
        { kind: "p", text: "She wants someone to see the person doing them." },
        { kind: "p", text: "The woman who existed before she became useful to everyone around her." },
        { kind: "p", text: "When you see that woman — specifically, not generally — something shifts in her." },
        { kind: "quote", text: "What She Hears" },
        { kind: "p", text: "“You're doing a great job.”" },
        { kind: "p", text: "She appreciates it. But it lands on the role, not the person. It confirms that what you see is her usefulness." },
        { kind: "quote", text: "What Reaches Her" },
        { kind: "p", text: "“I notice how much you carry. I see you - not just what you do.”" },
        { kind: "p", text: "This lands differently. It touches the woman, not the function." },
        { kind: "p", text: "The difference is not always in the words. It is in whether you are looking at her or looking at what she produces." },
        { kind: "p", text: "She can feel the difference without being able to explain it to you." },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "This week, ask her one question that has nothing to do with the household, the children, or the schedule." },
            { text: "Ask her about something she has put aside. A dream that got smaller. Something she used to love." },
            { text: "Then listen. Not to fix it. Not to plan it. Just to know it." },
            { text: "Remember what she says. Refer back to it three days later." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Before you ask her that question tonight, pause." },
            { text: "Look at her for three seconds without needing anything." },
            { text: "See her face. Not the woman who manages the house. Her actual face. The one you fell in love with." },
            { text: "Let your body register who she is before your mouth opens." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll ask the question and she may not answer straight away. She may deflect. She may laugh it off. She may test whether you actually care.",
            "That is not resistance. That is a woman who has been unseen for so long she does not trust the seeing yet.",
            "Stay. Ask again another day.",
            "Don't make it a project. Make it a quiet, ongoing curiosity.",
          ],
        },
        { kind: "p", text: "You stop being the man who appreciates what she does.", emphasis: "accent" },
        { kind: "p", text: "You become the man who sees who she is.", emphasis: "accent" },
      ],
    },
    {
      slug: "closeness-that-doesnt-lead-somewhere",
      order: 5,
      title: "Closeness That Doesn't Lead Somewhere",
      kind: "essay",
      image: "/unspoken-distance/closeness-that-doesnt-lead-somewhere.jpg",
      imageAlt: "A quiet, unhurried moment of closeness",
      imageSide: "right",
      body: [
        { kind: "p", text: "For many men intimacy means sex. For most women intimacy begins long before that." },
        { kind: "p", text: "If the only time she receives your physical attention is when you want something from her, her body learns to brace for touch rather than receive it." },
        { kind: "p", text: "The approach itself becomes a signal to prepare, not to open." },
        { kind: "p", text: "Hold her hand walking to the car." },
        { kind: "p", text: "Sit close to her when you don't need anything. Touch her lower back as you pass. Hug her for long enough that she stops counting the seconds." },
        { kind: "quote", text: "Touch that asks nothing is the touch that rebuilds trust in touch. I call it Touch That Lands." },
        { kind: "p", text: "This is not a technique." },
        { kind: "p", text: "It is a reorientation of what touch means between you." },
        { kind: "p", text: "When she stops expecting touch to want something from her, she can begin to receive it." },
        { kind: "p", text: "That is when the body starts to open again: not because you have done the right thing but because the condition of safety has begun to form." },
        { kind: "p", text: "Small. Consistent. Entirely without agenda." },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Right now, hold your own hand. Feel the weight of it. The temperature. The texture." },
            { text: "That is what touch without agenda feels like from the inside — contact that is not going anywhere." },
          ],
        },
      ],
    },
    {
      slug: "a-partner-not-just-a-provider",
      order: 6,
      title: "A Partner, Not Just a Provider",
      kind: "essay",
      image: "/unspoken-distance/transmitting-on-one-channel.jpeg",
      imageAlt: "A quiet, ordinary moment between two people",
      imageSide: "left",
      body: [
        { kind: "p", text: "She wants to feel that you are in it with her.", emphasis: "bold" },
        { kind: "p", text: "Not just in the external: the finances, the career, the logistics: but in the interior of your life together." },
        { kind: "p", text: "She is not asking you to be everything. She is asking you to be present." },
        { kind: "quote", text: "Be Interested in Her Interior Life" },
        { kind: "p", text: "Ask her what she wants. Not what she needs from you logistically. What she actually wants for herself. Then listen when she tells you. Remember what she says." },
        { kind: "quote", text: "Support Who She Is Becoming" },
        { kind: "p", text: "She has things she has put aside. Dreams that got smaller when the responsibilities got larger. She does not need you to fix this. She needs you to be interested in it." },
        { kind: "quote", text: "Be a Co-Creator, Not a Caretaker" },
        { kind: "p", text: "Carry some of the invisible weight without being asked. Notice what she is holding. Step into it. The most powerful thing you can say is: “I've got that. Don't worry about it.”" },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "This week, handle one thing she usually handles, without being asked and without announcing it." },
            { text: "Separately, ask her one question about something she wants for herself. Not for the family. For her." },
            { text: "Then remember what she says. Bring it up three days later." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Tonight, when you walk through the door, pause before you enter the room she's in." },
            { text: "Take one breath. Drop whatever you were thinking about on the drive home." },
            { text: "Walk in as though the most important meeting of your day is about to start, because it is." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll handle the logistics and feel proud of yourself.",
            "Then you'll forget the question. Or you'll ask it and half-listen because your mind is already on the next task.",
            "The interior question feels less urgent than the practical one. That hierarchy, logistics over intimacy, is the pattern.",
          ],
        },
        { kind: "p", text: "You stop being the man who is there for her on paper.", emphasis: "accent" },
        { kind: "p", text: "You become the man she feels standing next to her.", emphasis: "accent" },
      ],
    },
    {
      slug: "regaining-her-respect",
      order: 7,
      title: "Regaining Her Respect",
      eyebrow: "Part Two",
      kind: "essay",
      image: "/unspoken-distance/where-it-went.jpg",
      imageAlt: "A quiet moment of reflection",
      imageSide: "right",
      body: [
        { kind: "p", text: "Respect is not demanded. It is not negotiated. It is not restored by pointing out that it has been lost.", emphasis: "bold" },
        { kind: "p", text: "It is felt.", emphasis: "bold" },
        { kind: "quote", text: "Where It Went" },
        { kind: "p", text: "Ask yourself honestly." },
        { kind: "p", text: "Have you followed through on what you said you would do?" },
        { kind: "p", text: "Have you made decisions with confidence or deferred everything back to her?" },
        { kind: "p", text: "Have you been so focused on providing that you stopped being present?" },
        { kind: "p", text: "None of these make you a bad man. They make you a man who got busy and stopped leading. That is common. It is also fixable." },
        { kind: "quote", text: "Take Responsibility Without Collapse" },
        { kind: "p", text: "The fastest way to begin restoring respect is to own what has slipped: clearly, without defensiveness, without immediately explaining why." },
        { kind: "quote", text: "“I can see I haven't been showing up the way I should. That's changing.”" },
        { kind: "p", text: "One sentence of genuine ownership lands harder than an hour of justification. She is not looking for a perfect man. She is looking for a man who can see himself clearly and do something about it." },
        { kind: "quote", text: "Become Reliable in the Small Things" },
        { kind: "p", text: "If you say you will do something, do it. Not when reminded. Not eventually. When you said you would." },
        { kind: "p", text: "She cannot trust your direction if she cannot trust your word on an ordinary Tuesday." },
        { kind: "quote", text: "What Leading Actually Looks Like" },
        { kind: "p", text: "She doesn't want to make every decision. She wants to feel that you are capable of direction.", emphasis: "bold" },
        { kind: "step", label: "Small. Specific.", lines: [{ text: "“I thought we'd try that place tonight. Sound good?”" }] },
        { kind: "step", label: "Confident Without Being Rigid.", lines: [{ text: "“I'll handle the school thing. Don't worry about it.”" }] },
        { kind: "step", label: "Present, Not Performative.", lines: [{ text: "When she feels the steadiness behind the action, something in her relaxes. That relaxing is respect returning." }] },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Today, say one thing you have been holding back. Not to provoke. Not to prove a point." },
            { text: "Just to stop performing smallness." },
            { text: "Set one boundary without apologising for it." },
            { text: "Do one thing that is entirely yours, that builds your life, not the dynamic." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Stand with your feet on the floor. Feel your full height." },
            { text: "Feel the weight of holding your own position without scanning for approval." },
            { text: "That is what she needs to feel from you." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll hear 'reclaim your edge' and overcorrect.",
            "You'll say something with more charge than the situation calls for, or you'll set a boundary and immediately scan her face for approval.",
            "Both of these are the old pattern wearing a new costume.",
            "The goal is not to shock her with a new you. The goal is to stop performing smallness. Quietly. From inside.",
          ],
        },
        { kind: "p", text: "You stop being the man who waits for respect to return.", emphasis: "accent" },
        { kind: "p", text: "You become the man whose consistency makes it inevitable.", emphasis: "accent" },
      ],
    },
    {
      slug: "the-restaurant",
      order: 8,
      title: "The Restaurant",
      kind: "essay",
      image: "/unspoken-distance/the-restaurant-interior.jpg",
      imageAlt: "A fancy, modern restaurant interior",
      imageSide: "left",
      body: [
        { kind: "p", text: "Next time you take her somewhere, notice where her attention goes when you sit at a table in the middle of the room. How much of her is tracking who just came through the door. Registering the table behind her she cannot see. Watch her shoulders. Her breath." },
        { kind: "p", text: "Now choose her seat deliberately. Find somewhere she can put her back to a wall and see the room in front of her. Sit her there. Say nothing about why." },
        { kind: "p", text: "This is not anxiety. This is not a mood. This is her body doing what it has always done. Most women do this. Most have no idea they do it." },
        { kind: "p", text: "Her shoulders will drop. Her breath will slow. She will arrive more fully in the conversation. In the room. In her body." },
        { kind: "quote", text: "“I see you. I am paying attention to what your body needs before you know you need it. You are safe with me.”" },
        { kind: "p", text: "That is what leadership feels like from inside her nervous system. Not authority. Not control. Attunement." },
        { kind: "p", text: "She will not be able to explain why she felt more relaxed that evening. She will simply know that being with you felt different. That is enough. That is everything." },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Next time you take her somewhere, choose her seat deliberately." },
            { text: "Find somewhere she can put her back to a wall and see the room in front of her." },
            { text: "Sit her there. Say nothing about why." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Before you arrive, ground yourself. Use the zippers practice or Touch Base." },
            { text: "Walk in settled, not performing." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll do this once and watch for her response. If she doesn't react, you'll think it didn't work. It worked.",
            "She may not name it. The point is not her acknowledgment.",
            "The point is that you saw something her body needed before she had to ask, and you acted on it without requiring anything in return.",
          ],
        },
        { kind: "p", text: "You stop being the man who performs attentiveness.", emphasis: "accent" },
        { kind: "p", text: "You become the man who is actually paying attention.", emphasis: "accent" },
      ],
    },
    {
      slug: "reigniting-her-love",
      order: 9,
      title: "Reigniting Her Love",
      kind: "essay",
      image: "/unspoken-distance/closeness-that-doesnt-lead-somewhere.jpg",
      imageAlt: "A quiet, unhurried moment of closeness",
      imageSide: "right",
      body: [
        { kind: "p", text: "She can respect you and still feel far away. She can admire your reliability, your commitment, your presence in the family, and still struggle to feel the warmth that used to come naturally." },
        { kind: "p", text: "It is how love works in a body that doesn't feel fully safe yet, not contradiction." },
        { kind: "quote", text: "The Cycle Most Couples Are Stuck In" },
        { kind: "p", text: "You reach out. She pulls back. You feel rejected. You withdraw or push harder. She closes further. You both end up lonelier than before you tried." },
        { kind: "p", text: "Nobody intended this. Nobody is the villain. The cycle runs itself once it starts." },
        { kind: "p", text: "Understanding the cycle is the first step to stepping outside it. When you can see it clearly, you are no longer inside it in the same way." },
        { kind: "quote", text: "“You stop making her response the measure of whether you did it right.”" },
        { kind: "p", text: "When you untether your sense of doing well from her immediate response, something releases." },
        { kind: "p", text: "She is no longer managing your feelings alongside hers." },
        { kind: "p", text: "She can just be where she is." },
        { kind: "p", text: "That freedom is often the first thing that lets her start moving toward you again." },
        { kind: "p", text: "You stop being the man whose sense of doing well depends on her response.", emphasis: "accent" },
        { kind: "p", text: "You become the man who shows up regardless.", emphasis: "accent" },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Put both feet flat on the floor." },
            { text: "Take one breath in. Notice where it settles: chest, belly, somewhere tighter." },
            { text: "Whatever is there, let it be there." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll do this practice and then immediately test whether it changed anything.",
            "You'll approach her grounded and within thirty seconds start tracking: is she softer? Is she turning toward me? Is this working?",
            "That tracking is the agenda. She can feel you leave the grounding the moment you start measuring.",
            "The practice has to be the end point, not the beginning of a strategy.",
          ],
        },
      ],
    },
    {
      slug: "the-grounding-practice",
      order: 10,
      title: "The Grounding Practice",
      kind: "essay",
      image: "/unspoken-distance/the-grounding-practice.png",
      imageAlt: "A grounded, quiet moment",
      imageSide: "left",
      body: [
        { kind: "p", text: "Before you approach her, your body matters.", emphasis: "bold" },
        { kind: "p", text: "What you are carrying when you walk toward her: the day, the frustration, the hope, the neediness, she will feel all of it before you speak." },
        {
          kind: "step",
          label: "Ground Yourself First",
          lines: [
            { text: "Imagine you have small zippers in the soles of your feet and the palms of your hands." },
            { text: "Take a breath in. As you exhale, open those zippers." },
            { text: "Imagine everything you are carrying, the day, the stress, the outcome you are hoping for, draining down through your feet and your hands. Out into the floor." },
            { text: "Do this three times." },
            { text: "Notice what happens in your torso. A slight heaviness. A settling. The beginning of actually being here rather than somewhere ahead of yourself." },
            { text: "That is what she is waiting to feel from you.", emphasis: "bold" },
          ],
        },
        { kind: "quote", text: "Checking Capacity Before You Begin" },
        { kind: "p", text: "Timing is not about finding the right moment. It is about reading whether a moment exists at all." },
        { kind: "p", text: "Before you approach her: are you actually present, or still half in something else? Is there an outcome you are already hoping for? Is there frustration underneath the reaching?" },
        { kind: "p", text: "She will feel all of that before you say a word." },
        { kind: "p", text: "Then read her." },
        { kind: "p", text: "Has she just come off a full day with the children or work? Is her body turned away, occupied, somewhere else entirely?" },
        { kind: "p", text: "Waiting for the right moment is not passive. It is one of the most respectful things you can do.", emphasis: "bold" },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Before you approach her, ground yourself first. Zippers practice. Three breaths." },
            { text: "Then Touch Base if the pattern fires in real time." },
            { text: "Check your own capacity before you reach for her." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll do this practice and then immediately test whether it changed anything.",
            "You'll approach her grounded and within thirty seconds start tracking: is she softer? Is she turning toward me? Is this working?",
            "That tracking is the agenda. She can feel you leave the grounding the moment you start measuring.",
            "The practice has to be the end point, not the beginning of a strategy. Ground yourself. Approach her. Let whatever happens be enough.",
            "If you find yourself unable to stop tracking her response, that pattern is deeper than a practice can reach. That is what the 1:1 Intensive is designed for: we go directly to the pattern running underneath your reaching and we shift it. Four sessions. Six weeks. You will feel the difference immediately.",
          ],
        },
      ],
    },
    // ------------------------------------------------------------- video
    {
      slug: "the-groundedness-practice",
      order: 11,
      title: "The Groundedness Practice",
      kind: "essay",
      image: "/unspoken-distance/the-grounding-practice.png",
      imageAlt: "A grounded, quiet moment",
      imageSide: "right",
      body: [
        { kind: "p", text: "This is the practice underneath everything else in this guide." },
        { kind: "p", text: "Groundedness builds the way a muscle does, through repetition. The same few minutes, returned to on purpose, week after week." },
        { kind: "p", text: "Press play before you approach her tonight. Press play again next week. Let it become the practice you keep coming back to, the way you keep coming back to breath.", emphasis: "accent" },
        { kind: "video", vimeoId: "1208083538" },
      ],
    },
    {
      slug: "why-she-wants-to-be-led",
      order: 12,
      title: "Why She Wants to Be Led",
      eyebrow: "Part Four",
      kind: "essay",
      image: "/unspoken-distance/why-she-wants-to-be-led.jpg",
      imageAlt: "A quiet moment between two people",
      imageSide: "left",
      body: [
        { kind: "p", text: "This is the section most men are afraid to read." },
        { kind: "p", text: "Not because it asks too much of them. Because it names something they have been hoping wasn't true." },
        { kind: "p", text: "She is exhausted from leading.", emphasis: "bold" },
        { kind: "p", text: "Not from working. Not from parenting." },
        { kind: "p", text: "From carrying the emotional direction of the relationship. From being the one who notices when things are off. From managing the distance between you while pretending it isn't there." },
        { kind: "p", text: "When a woman stops trying, it is not indifference. It is the end of a very long effort." },
        { kind: "quote", text: "What She Actually Wants" },
        { kind: "p", text: "She wants to feel led." },
        { kind: "p", text: "Not controlled. Not managed. Not told what to do." },
        { kind: "p", text: "She wants to feel that you have the situation." },
        { kind: "p", text: "That she can put something down and it will be held." },
        { kind: "quote", text: "“She can just be a woman with you.”" },
        { kind: "quote", text: "What Leadership Is Not" },
        { kind: "p", text: "It is not making every decision. It is not asserting your position. It is not having all the answers." },
        { kind: "p", text: "Leadership in a relationship is quieter than that. It is emotional steadiness when things get hard. It is staying present when her feelings are large. It is the willingness to hold the container so she doesn't have to hold it and be in it at the same time." },
        { kind: "quote", text: "The Shift from Pressure to Pleasure" },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "This week, make one decision without asking her what she wants first." },
            { text: "Something small. A restaurant. A plan for Saturday. A problem you handle without putting it back on her plate." },
            { text: "Say: “I've got this. Don't worry about it.”" },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Stand up. Feel your feet on the floor. Feel your full height." },
            { text: "Now, without changing your posture, feel the weight of your own decisions sitting in your chest. Not heavy. Settled." },
            { text: "That is what she needs to feel radiating from you when you walk into the room." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll make a decision and immediately second-guess it. Or you'll make it and then check whether she's happy with it.",
            "Both of these hand the lead back to her.",
            "Stay with the decision. If it's not perfect, that is fine.",
            "A man who makes an imperfect decision and owns it is more attractive than a man who defers everything to keep the peace.",
          ],
        },
        { kind: "p", text: "You stop being the man she has to manage.", emphasis: "accent" },
        { kind: "p", text: "You become the man she can relax into.", emphasis: "accent" },
      ],
    },
    {
      slug: "structured-communication",
      order: 13,
      title: "Structured Communication",
      eyebrow: "Part Five",
      kind: "essay",
      image: "/unspoken-distance/the-problem-solving-trap.jpg",
      imageAlt: "A quiet conversation between two people",
      imageSide: "right",
      body: [
        { kind: "p", text: "Most communication problems in a relationship are not about what is being said. They are about what is happening in the body while it is being said." },
        { kind: "p", text: "You are tense. She is braced. Neither of you is actually in the conversation. You are both in the conversation you are afraid is about to happen." },
        {
          kind: "notice",
          lines: [
            { text: "The Pattern", emphasis: "bold" },
            { text: "She starts talking. Within thirty seconds you are already solving the problem in your head. You offer the solution. She goes quiet." },
            { text: "You thought you were helping. She felt dismissed." },
          ],
        },
        {
          kind: "notice",
          lines: [
            { text: "What's Really Happening", emphasis: "bold" },
            { text: "She was not looking for a solution. She was looking to feel that you understood." },
            { text: "When you skip the feeling and go straight to the fix, she learns to stop sharing, not angrily, just quietly. That quiet is not peace. That quiet is her giving up on being heard by you." },
            { text: "Connect first. Solve later.", emphasis: "bold" },
          ],
        },
        { kind: "quote", text: "The Problem-Solving Trap" },
        { kind: "p", text: "When she comes to you with something that is bothering her and you move immediately to solutions, she feels dismissed." },
        { kind: "p", text: "Not because you said anything wrong." },
        { kind: "p", text: "Because you skipped the part that mattered to her." },
        { kind: "p", text: "She wasn't looking for a solution." },
        { kind: "p", text: "She was looking to feel that you understood." },
        { kind: "quote", text: "How to Actually Listen" },
        { kind: "p", text: "When she is speaking, face her. Make eye contact. Let your body be still. When she pauses, don't fill it immediately. The next thing is often the real thing." },
        { kind: "p", text: "When she finishes, respond with what you heard." },
        {
          kind: "step",
          label: "Reflect Back What You Heard",
          lines: [
            { text: "“That sounds like it has been weighing on you for a while.”" },
            { text: "“I can hear how frustrated you are.”" },
            { text: "“That makes sense.”" },
          ],
        },
        { kind: "p", text: "Not agreement necessarily. Acknowledgment that you received it. That small act, simply reflecting back what she said, can shift the entire temperature of a conversation." },
        { kind: "quote", text: "How to Express What You Need Without Starting a Fight" },
        { kind: "step", label: "Check Capacity", lines: [{ text: "“Is now a good time, or would later work better?”" }] },
        { kind: "step", label: "Express How You Feel, Not What She Did", lines: [{ text: "“I have been feeling disconnected lately,” not “you have been distant.”" }] },
        { kind: "step", label: "Make a Specific Request", lines: [{ text: "“Can we set aside some time this week just for us?”" }] },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Step 1: Check capacity. “Is now a good time, or would later work better?”" },
            { text: "Step 2: Reflect, don't fix. Respond with what you heard, the feeling underneath, not the content." },
            { text: "Step 3: Ask before solving. “Would you like help thinking through it, or do you just need me to hear you?”" },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Before the conversation, feet on the floor." },
            { text: "When she pauses and your body wants to fill it, notice the impulse. Let it pass." },
            { text: "Stay with her silence instead of solving it." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll start the conversation well and then slip into fixing mode the moment she pauses.",
            "Your body will register the pause as a problem to solve. That impulse is not a failure, it is the pattern.",
            "Notice it. Name it silently. Return to her.",
          ],
        },
        { kind: "p", text: "You stop being the man who fixes.", emphasis: "accent" },
        { kind: "p", text: "You become the man she can talk to.", emphasis: "accent" },
      ],
    },
    {
      slug: "the-intimacy-and-communication-cards",
      order: 14,
      title: "The Intimacy and Communication Cards",
      kind: "essay",
      image: "/unspoken-distance/cards-template.png",
      imageAlt: "The Intimacy and Communication Cards, card template",
      imageSide: "left",
      body: [
        { kind: "p", text: "We all want to be seen, heard, and ultimately understood." },
        { kind: "p", text: "When we listen, we often listen to interject, fix, or are already making up the response in our minds. This stops that. It brings in structure." },
        { kind: "p", text: "Set a timer for fifteen minutes. Be somewhere quiet. One of you reads the prompt out loud:" },
        { kind: "p", text: "The other answers from the heart." },
        { kind: "p", text: "No interrupting." },
        { kind: "p", text: "No fixing." },
        { kind: "p", text: "No debating what they say." },
        {
          kind: "step",
          label: "Three Responses Only",
          lines: [
            { text: "“Thank you.” — I heard you." },
            { text: "“Clarify that.” — I want to understand more." },
            { text: "“Summarise that.” — Say the most important part simply." },
            { text: "Then switch. Fifteen minutes. One prompt. No agenda beyond hearing each other." },
          ],
        },
        { kind: "p", text: "What shifts in that container is remarkable." },
        { kind: "p", text: "I have watched couples who hadn't really spoken in years find each other again in fifteen minutes with one prompt." },
        { kind: "p", text: "These prompts are from the Intimacy and Communication Cards, created for exactly this kind of conversation. Physical cards and a digital app. Each one goes one layer deeper than the last." },
        { kind: "image", src: "/unspoken-distance/cards-app-screenshot.png", alt: "The Intimacy and Communication Cards app" },
        { kind: "link", text: "Get the Cards →", href: "https://shop.feelfullyyou.com/cards-1" },
        { kind: "link", text: "Try the App →", href: "https://couplecards.netlify.app/free" },
        { kind: "image", src: "/unspoken-distance/cards-physical-deck.jpg", alt: "The physical Intimacy and Communication Cards deck" },
        { kind: "p", text: "I wrote about how the cards came to be." },
        { kind: "p", text: "Not just because I use them with couples, but how an exact structured prompt like this helped me in a really dark time in my life." },
        { kind: "p", text: "I call it Clearing the Pipes. I used this exact method to write the eulogy for my sister when I was completely stuck." },
        { kind: "link", text: "Read it, What the Body Knows by Juliette Karaman", href: "http://juliette.substack.com" },
        { kind: "image", src: "/unspoken-distance/clearing-the-pipes-substack.png", alt: "Clearing the Pipes, on What the Body Knows by Juliette Karaman" },
      ],
    },
    {
      slug: "the-hidden-trauma",
      order: 15,
      title: "The Hidden Trauma",
      eyebrow: "Part Six",
      kind: "essay",
      image: "/unspoken-distance/three-minute-timer.jpg",
      imageAlt: "A three minute countdown timer",
      imageSide: "right",
      body: [
        { kind: "p", text: "This is the section most guides skip. It's important, yet it is uncomfortable to name." },
        { kind: "p", text: "Her body may be holding something that has nothing to do with you and everything to do with why she cannot open." },
        { kind: "p", text: "It may not be what you think of when you hear the word trauma. It may not be a single event. It may be something she has never consciously identified." },
        { kind: "quote", text: "“The body stores the learning, not the story.”" },
        { kind: "quote", text: "What Trauma Looks Like in the Body" },
        { kind: "p", text: "It lives in the slight stiffening of her spine when you reach for her unexpectedly. The way her shoulders rise. The way she goes somewhere else in the middle of a moment that should feel close." },
        { kind: "p", text: "It lives in the way her body sometimes says no before her mind has had a chance to weigh in." },
        { kind: "p", text: "This is protection. Not rejection." },
        { kind: "p", text: "You cannot argue her out of it. What reaches it is felt safety, accumulated over time. The repeated experience of being close to you and nothing going wrong." },
        { kind: "quote", text: "Why Touch Is the Centre of This Work" },
        { kind: "p", text: "Touch is not a small part of rebuilding." },
        { kind: "p", text: "It is the mechanism.", emphasis: "accent" },
        { kind: "p", text: "When her body receives safe touch, her nervous system shifts. Oxytocin rises. Cortisol drops. Her blood pressure lowers. Her vagus nerve activates, moving her from vigilance into rest." },
        { kind: "p", text: "Research on couples shows that a partner's touch produces higher oxytocin and lower cortisol than anyone else's." },
        { kind: "p", text: "Your touch has more power to calm her nervous system than any other person on this planet." },
        { kind: "p", text: "But if the touch arrives without structure, if it has no beginning and no end, if she does not know what she is saying yes to or how long it will last, her body cannot settle into it." },
        { kind: "p", text: "It stays on alert. Waiting. Managing." },
        { kind: "p", text: "A body that braces cannot relax into the unknown." },
        { kind: "p", text: "But it can relax into three minutes. It can say yes to something with edges.", emphasis: "bold" },
        { kind: "p", text: "“I would love to hold you in a hug for three minutes. Do you have capacity for that?”", emphasis: "bold" },
        { kind: "p", text: "That sentence does more than ask. It tells her exactly what is coming. How long it will last. That she will not have to guess when it is over or what comes next." },
        { kind: "p", text: "That is what a time container does. It makes the unknown safe enough to feel." },
        { kind: "p", text: "If she says yes, hold her." },
        { kind: "p", text: "Nothing else. No talking unless she wants to. No shifting into something more." },
        { kind: "p", text: "When the three minutes are up, let go gently." },
        { kind: "p", text: "That is it." },
        { kind: "p", text: "If she says not right now, that is not rejection." },
        { kind: "p", text: "That is a woman who can feel her own edges." },
        { kind: "p", text: "This is the structure we use in The Beginning, the Ultimate Touch Reset." },
        { kind: "p", text: "Every touch date has a container. A beginning, a middle, an end. A time." },
        { kind: "p", text: "Nothing open-ended. Nothing she has to manage or guess her way through. When the body knows the edges, it can stop scanning and start receiving." },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Start with yourself. Notice the quality of your own touch throughout the day. How you pick up your keys. How your hand rests on the steering wheel." },
            { text: "Slow one of those down. Feel the contact before you move on." },
            { text: "When you are ready to reach for her, bring structure." },
            { text: "“I would love to hold you for three minutes. Do you have capacity for that?”" },
            { text: "Set a timer if you need to. She does not have to wonder when it ends. You do not have to guess if you are holding too long. The timer holds it for both of you." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Hold your own hands together for ten seconds. Feel what your hands feel like when they are not reaching for anything. Warm. Heavy. Still." },
            { text: "Now let them open. Rest them on your legs, palms up." },
            { text: "Notice the difference. One is holding. One is receiving." },
            { text: "That is the quality she needs to feel from you." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You will ask and it will feel mechanical. You will think: she's my wife, why do I need to ask to hold her?",
            "Because her body has been saying no while her mouth has been saying nothing. The structure gives her a way to say yes that is real.",
            "You will hold her and start counting. You will notice your own body getting restless or aroused. She can feel that.",
            "This is not about controlling your response. It is about noticing it without acting on it.",
            "The moment you can hold her, feel your own desire, and still let the three minutes be about contact with no next step, that is the shift.",
            "If her body is holding something that needs more than patience and structure, if there is a pattern of freezing, bracing, or leaving the room during closeness, this is deeper work than a guide can reach.",
            "This is what I have been doing for 27 years. 980 women. 650 couples. The body holds it until someone who knows what they are looking at helps it let go.",
          ],
        },
        { kind: "p", text: "You stop being the man who pushes through her guard.", emphasis: "accent" },
        { kind: "p", text: "You become the man whose presence makes the guard unnecessary.", emphasis: "accent" },
      ],
    },
    {
      slug: "her-love-touch-and-pleasure-language",
      order: 16,
      title: "Her Love Language, Touch Language and Pleasure Language",
      eyebrow: "Part Seven",
      kind: "essay",
      image: "/unspoken-distance/love-languages.jpeg",
      imageAlt: "A quiet, tender moment",
      imageSide: "left",
      body: [
        { kind: "p", text: "Here is something most couples never discover. The way she experiences love, touch, and connection is completely specific to her. It operates on three layers, and most guides only cover one." },
        { kind: "quote", text: "Layer One: Love Languages" },
        { kind: "p", text: "These are Gary Chapman's five Love Languages." },
        { kind: "p", text: "You may already know them." },
        { kind: "p", text: "If you do, you are ahead of most men reading this." },
        { kind: "p", text: "I make a distinction in how you like to give and how you like to receive love, and what you are patterned in." },
        { kind: "quote", text: "how she feels emotionally loved" },
        {
          kind: "step",
          label: "The Five Love Languages",
          lines: [
            { text: "Words of Affirmation: she feels loved when you say something specific about who she is, not what she does." },
            { text: "Acts of Service: she feels loved when you handle something without being asked." },
            { text: "Receiving Gifts: she feels loved when you remember, notice, and act on it." },
            { text: "Quality Time: she feels loved when you are present, undistracted, actually there." },
            { text: "Physical Touch: she feels loved through non-sexual contact that asks nothing." },
          ],
        },
        { kind: "p", text: "If you don't know hers, ask yourself: what does she complain about most? That complaint is her unmet love language turned into frustration." },
        { kind: "p", text: "Love Languages tell you what makes her feel emotionally loved. They do not tell you how her body experiences touch. That is a different language entirely." },
        { kind: "quote", text: "Layer Two: Touch Languages" },
        { kind: "image", src: "/unspoken-distance/touch-languages.jpg", alt: "Touch Languages" },
        { kind: "p", text: "Most people have a primary. Most couples have never identified theirs, or each other's." },
        { kind: "p", text: "If you have been reaching for her in your language, she may have been feeling reached for rather than reached." },
        { kind: "p", text: "Together, Love Languages and Touch Languages show you two things: what has her feel emotionally loved, and how her being actually receives connection, how she is touched by life." },
        { kind: "p", text: "When these are mismatched between you, and they almost always are, every reach you make doesn't land, or lands slightly off. Not wrong. Just not quite hers." },
        { kind: "p", text: "Maybe not even yours. You may not be fluent in her language, or even be aware you have these different ways of being touched by life." },
        {
          kind: "step",
          label: "The Five Touch Languages",
          lines: [
            { text: "Emotional: touch that carries feeling. The way you allow her emotions to be expressed without flinching." },
            { text: "Energetic: connection through the field between bodies. Presence felt across a room. The electricity of almost." },
            { text: "Erotic: touch that awakens aliveness and desire." },
            { text: "Physical: non-erotic. The weight of a heavy blanket. Solid, grounding contact." },
            { text: "Spiritual: touch that reaches something beyond the physical. Reverence. Being held as something sacred." },
          ],
        },
        { kind: "p", text: "All of it makes a difference in how physical and erotic touch starts to show up." },
        { kind: "p", text: "That's why the Pleasure Languages are next." },
        { kind: "p", text: "Love Languages and Touch Languages show you how she feels loved and how her body receives connection. They do not tell you what awakens desire in her. That is a different language entirely, and crucial to understand." },
        { kind: "quote", text: "Layer Three: Pleasure Languages" },
        { kind: "image", src: "/unspoken-distance/pleasure-languages.jpg", alt: "Pleasure Languages" },
        { kind: "p", text: "If you have been reaching for her in your language, she may have been feeling reached for rather than reached." },
        { kind: "quote", text: "The Pleasure Languages" },
        { kind: "quote", text: "what awakens desire in her" },
        { kind: "p", text: "Jaiya's Erotic Blueprint framework, which I am trained in, maps five ways people experience pleasure and desire: Energetic. Sensual. Sexual. Kinky. Shapeshifter." },
        { kind: "p", text: "Most people are a blend. Most couples have never mapped this together." },
        { kind: "p", text: "If your approaches to intimacy have felt mismatched, this may be why. Not incompatibility. Different languages, never translated." },
        {
          kind: "step",
          label: "The Five Pleasure Languages",
          lines: [
            { text: "Energetic: aroused by anticipation, space, and the charge between bodies. Too much too fast shuts her down." },
            { text: "Sensual: needs all the senses engaged. Atmosphere, texture, scent, sound. The whole environment matters." },
            { text: "Sexual: direct, explicit, confident. She knows what she wants and responds to someone who does too." },
            { text: "Kinky: aroused by the taboo, power dynamics, or the unexpected. Psychological as much as physical." },
            { text: "Shapeshifter: a blend of all types. Needs variety. Can feel hard to read, because she contains all of it." },
          ],
        },
        { kind: "quote", text: "The Three Together" },
        { kind: "p", text: "When all three are visible, everything about how you reach for each other changes. Not because you try harder, because you finally understand the frequency she is on." },
        {
          kind: "step",
          label: "What Each Layer Tells You",
          lines: [
            { text: "Love Languages tell you what she needs emotionally." },
            { text: "Touch Languages show you how she is moved by life and touch." },
            { text: "Pleasure Languages reveal what awakens desire in her." },
          ],
        },
        { kind: "p", text: "No other guide will give you all three. Because no other practitioner in this space works across all three layers.", emphasis: "bold" },
        { kind: "p", text: "In The Beginning: The Ultimate Touch Reset, this is one of the first things we map together." },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Start by noticing which language you default to. Not which one you think you speak. Which one your body reaches for without thinking." },
            { text: "Do you show love by doing things? By touching? By being there? That is your default. It may not be hers." },
            { text: "This week, ask her. Not as a quiz. As a genuine question." },
            { text: "“Tell me, what makes you feel most loved by me? Not what I do for the family. What makes you feel it in your body?”" },
            { text: "Listen to what she says. She may not have words for it yet. She may say something that surprises you. She may say ‘I don't know.’ That answer is worth more than a quick one, because it means she has never been asked in a way that let her feel for the answer." },
            { text: "Then notice your own. When do you feel most connected to her? When she touches you? When she sees you? When she says something that lands? That is your language. It may be completely different from hers. It usually is." },
            { text: "You are not trying to fix anything this week. You are learning two languages you never knew existed." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Put your hand flat on the table in front of you. Feel it resting there. Just weight and temperature." },
            { text: "Now, without moving your hand, think about how much you appreciate her. Let the feeling come. Not a thought about her. A feeling." },
            { text: "Your hand did not move. But the quality changed." },
            { text: "Now shift again. Think about wanting something from her. A response. A softening. A sign that this is working." },
            { text: "Feel what changes in your hand. The slight tension. The reaching underneath the stillness." },
            { text: "If she were underneath that hand right now, she would feel the difference between the two. Every single time." },
            { text: "That is what Touch Languages are. The same gesture. Completely different transmission. She is reading the transmission, not the gesture. She always has been." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You will default to your own language within 48 hours because it is automatic.",
            "You will think you are speaking hers but you will unconsciously twist it into yours.",
            "You may ask the question and then not hear the answer because it doesn't match what you expected.",
            "Or you will hear it, try it once, and when it feels awkward you will go back to what is comfortable.",
            "This is not resistance. This is neural default. The pathway you have used for years is stronger than the one you are building.",
          ],
        },
        { kind: "p", text: "You stop being the man who loves her in his language.", emphasis: "accent" },
        { kind: "p", text: "You become the man who learned hers.", emphasis: "accent" },
        { kind: "p", text: "In The Beginning, this is one of the first things we map together. His Touch Language. Her Touch Language. Where they overlap and where they miss. The full mapping, not just the preference but the pattern underneath it, is what makes everything about how you reach for each other shift." },
        { kind: "p", text: "That depth cannot happen in a PDF. It needs someone who can see what your body is doing while you are doing it." },
      ],
    },
    {
      slug: "rebuilding-trust",
      order: 17,
      title: "Rebuilding Trust",
      eyebrow: "Part Eight",
      kind: "essay",
      image: "/unspoken-distance/rebuilding-trust.jpg",
      imageAlt: "Two people rebuilding closeness",
      imageSide: "right",
      body: [
        { kind: "p", text: "Trust is not a decision she makes. It is a feeling she has in her body when she is with you." },
        { kind: "quote", text: "What Trust Actually Is" },
        {
          kind: "step",
          label: "The Three Safeties",
          lines: [
            { text: "Emotional Safety: can she tell you the truth without it being met with your own reaction that she then has to manage?" },
            { text: "Physical Safety: does her body relax when you are close, or does it prepare?" },
            { text: "Energetic Safety: does your presence steady her, or does it ask something of her?" },
          ],
        },
        { kind: "p", text: "If any of these is missing, intimacy will be limited. Not because she is choosing to limit it. Because her body will not allow the full opening that genuine intimacy requires." },
        { kind: "quote", text: "The Micro-Actions Practice" },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "For the next 14 days, choose one area where you have been inconsistent. Commit to complete follow-through." },
            { text: "If you say you will text her, text her. If you say you will be home at a particular time, be home at that time." },
            { text: "At the end of 14 days, ask her: “Have you noticed anything different?”" },
            { text: "Do not point out what you have been doing. Let her notice.", emphasis: "bold" },
          ],
        },
        { kind: "quote", text: "Rebuilding Trust in Intimacy" },
        { kind: "p", text: "Hold her for five minutes a day with no agenda. No words unless she wants them. Ask her: does this feel okay? Let her guide how she wants to be held." },
        { kind: "p", text: "When she pulls away, let her. Do not hold tighter. Let her go and stay warm." },
        { kind: "quote", text: "“Trust in the body is built through being allowed to say no and having nothing break.”" },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Think of a time this week when you said you would do something and didn't. Don't justify it." },
            { text: "Just sit with the gap between your word and your action." },
            { text: "Feel what that gap feels like in your body, the tightness, the slight heat of knowing." },
            { text: "That is what she feels every time. Except she feels it in the space between you." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll do the 14 days and on day 9 you'll slip. You'll forget to text. You'll be late.",
            "Here is the critical moment: what you do after you slip matters more than the slip itself.",
            "A man who says ‘I said I'd text and I didn't, I'm sorry, that wasn't good enough’ and then gets back on it, that man is building trust faster than the man who never slips but never owns it when he does.",
          ],
        },
        { kind: "p", text: "You stop being the man who announces he has changed.", emphasis: "accent" },
        { kind: "p", text: "You become the man she feels has changed.", emphasis: "accent" },
      ],
    },
    {
      slug: "sustaining-what-you-build",
      order: 18,
      title: "Sustaining What You Build",
      eyebrow: "Part Nine",
      kind: "essay",
      image: "/unspoken-distance/date-night.jpg",
      imageAlt: "A couple on a date at night",
      imageSide: "left",
      body: [
        { kind: "p", text: "Everything in this guide can be undone by stopping. Connection is not a destination. It is a practice." },
        { kind: "quote", text: "Keep Polarity Alive" },
        { kind: "image", src: "/unspoken-distance/keep-polarity-alive.png", alt: "Yin and yang, polarity" },
        { kind: "p", text: "Stay in your own life." },
        { kind: "p", text: "Have direction." },
        { kind: "p", text: "Have things that matter to you beyond the relationship." },
        { kind: "quote", text: "“Be a man who is going somewhere rather than one who has arrived and stopped moving.”" },
        { kind: "quote", text: "Create Rituals" },
        {
          kind: "step",
          label: "Daily, Weekly, Monthly",
          lines: [
            { text: "Daily: a ten-minute check-in at the end of the day. No screens. Just the two of you." },
            { text: "Weekly: a time that is only yours. Consistent and protected." },
            { text: "Monthly: something new together. Novelty keeps both of you present with each other." },
          ],
        },
        { kind: "quote", text: "Keep Erotic Tension Alive" },
        { kind: "p", text: "Flirt with her like you did before the relationship became a household to manage." },
        { kind: "p", text: "Send her a message in the middle of the day that has nothing to do with logistics. Plan something she doesn't know about." },
        { kind: "quote", text: "Mystery is not manipulation. It is the space between you that keeps desire alive." },
        { kind: "quote", text: "Keep Growing" },
        { kind: "p", text: "A man who has stopped growing is not easy to stay close to." },
        { kind: "p", text: "Stay curious." },
        { kind: "p", text: "Challenge yourself. Have goals that are yours." },
        { kind: "p", text: "Take care of your body: not for appearance but because a man who is in his body is easier to be close to than one who has retreated from it." },
        { kind: "p", text: "The woman beside you is also growing. The relationship needs to have room for both of you to be in motion." },
        { kind: "p", text: "Stagnation in one partner eventually contracts the other. Stay moving. Stay interested. Stay alive to what is possible." },
        {
          kind: "step",
          label: "The Practice",
          lines: [
            { text: "Daily: one moment of actual presence, no agenda. Phone down, eyes up, actually there." },
            { text: "Weekly: one real conversation that goes somewhere beyond logistics." },
            { text: "Monthly: return to the section that has slipped. Work it." },
          ],
        },
        {
          kind: "step",
          label: "Embodiment Exercise",
          lines: [
            { text: "Right now, put your phone face down. For the next sixty seconds, just be here. No checking. No scrolling. No input. Just you, your body, this room." },
            { text: "That is your daily practice. Sixty seconds of actual presence. Start tonight." },
          ],
        },
        {
          kind: "promptGroup",
          category: "How This Pattern Will Show Up",
          color: "blueGrey",
          prompts: [
            "You'll do these practices for three weeks. Maybe four. Then life will get busy and you'll stop. Not dramatically, just quietly.",
            "One missed evening becomes a missed week becomes ‘I'll get back to it.’",
            "She will feel you leave before you notice you left.",
            "The pattern is not the stopping. The pattern is not noticing you stopped.",
            "Come back to this page when you realise. That is the practice, the returning.",
          ],
        },
        { kind: "p", text: "You stop being the man who tried something once.", emphasis: "accent" },
        { kind: "p", text: "You become the man who chose a standard and kept choosing it.", emphasis: "accent" },
      ],
    },
    // ----------------------------------------------------------- closing
    {
      slug: "meet-juliette",
      order: 19,
      title: "Meet Juliette",
      eyebrow: "Intimacy and touch expert",
      kind: "closing",
      image: "/unspoken-distance/juliette-karaman-portrait.jpg",
      imageAlt: "Juliette Karaman",
      imageSide: "right",
      body: [
        { kind: "image", src: "/unspoken-distance/juliette-karaman-portrait.jpg", alt: "Juliette Karaman" },
        { kind: "p", text: "Intimacy and touch expert." },
        { kind: "p", text: "Touch Base® · The Touch Languages™ · Rapid Release Rewire and Restore®" },
        { kind: "p", text: "I create experiences. Experiences for the moments when you understand what's happening in your body, and still something tightens or fades when closeness begins." },
        { kind: "p", text: "For over 27 years, I've worked with how people feel, relate, and connect across mind, nervous system, body, and relationship. My work began with children on the spectrum, helping them trust sensation before they had words for it. That early work shaped everything that followed." },
        { kind: "p", text: "What I've seen again and again is simple: insight alone doesn't change intimacy." },
        { kind: "p", text: "Touch alone doesn't either. Change happens through experiences the body can stay present with." },
        { kind: "p", text: "Most intimacy doesn't fall apart in conflict. It slips away at the beginning. A reach. A hesitation. A moment neither knows how to hold." },
        { kind: "p", text: "I don't fix relationships. I don't offer techniques." },
        { kind: "p", text: "I design clear, guided experiences that meet people exactly where intimacy usually collapses, so touch can start to feel possible again." },
        { kind: "p", text: "The couples I work with don't just understand themselves better." },
        { kind: "p", text: "They feel different. They touch differently. They stay in connection.", emphasis: "bold" },
        { kind: "p", text: "My work has been featured in Forbes, Cosmopolitan, The Telegraph, ITV, FOX, and CBS." },
        {
          kind: "step",
          label: "27 Years, 650+ Couples, 980+ Women",
          lines: [
            { text: "Twenty-seven years working at the intersection of body, intimacy, and human connection." },
            { text: "650+ couples held at the edge of distance, through to something new." },
            { text: "980+ women supported back into themselves, their bodies, and their desire." },
          ],
        },
        { kind: "p", text: "Host of The Scrumptious Woman® Podcast, top 2.5% worldwide." },
        { kind: "link", text: "feelfullyyou.com", href: "https://feelfullyyou.com" },
        { kind: "link", text: "What the Body Knows by Juliette Karaman, on Substack", href: "http://juliette.substack.com" },
        { kind: "quote", text: "“Her withdrawal is not a verdict on you. It is an invitation to understand something you were never taught.”" },
      ],
    },
    {
      slug: "your-next-yes",
      order: 20,
      title: "Your Next Yes",
      kind: "closing",
      image: "/unspoken-distance/touchpoint-for-men.jpg",
      imageAlt: "Touchpoint, for the men",
      imageSide: "left",
      body: [
        { kind: "p", text: "The pattern you just recognised in yourself? It has been running for years." },
        { kind: "p", text: "Possibly decades. It is stored in your body, not your mind. Reading about it is not the same as changing it." },
        { kind: "p", text: "Put your hand on your chest for a moment. Feel your own heartbeat underneath your palm. The man who read this entire guide and is still here, who didn't look away, who didn't defend, who stayed, that is the man she needs to meet." },
        { kind: "p", text: "This wasn't just a guide. It was your first insight to what may be happening for her and how you can change how you show up in your relationship." },
        { kind: "p", text: "Insight is good, but what if you could actually be guided through what to do right there and then, and it is only a fraction of what working with me privately looks like?" },
        { kind: "image", src: "/unspoken-distance/touchpoint-for-men.jpg", alt: "Touchpoint, for the men" },
        {
          kind: "step",
          label: "Touchpoint, For the Men — a Monthly Membership",
          lines: [
            { text: "A daily channel with me, for the men who keep asking what to do." },
            { text: "Pointers every day on how to hold space for a woman, and a live call once a month." },
          ],
        },
        { kind: "link", text: "Join Touchpoint", href: "https://feelfullyyou.com/touch-point" },
        { kind: "quote", text: "Work With Me" },
        { kind: "p", text: "Some of you may already be ready to take this to the next level with my mentorship. Below are the ways to do so." },
        { kind: "quote", text: "The 1:1 Intensive" },
        { kind: "image", src: "/unspoken-distance/the-1-1-intensive.png", alt: "The 1:1 Intensive" },
        { kind: "p", text: "If something specific surfaced while you were reading." },
        { kind: "p", text: "One pattern. One block." },
        { kind: "p", text: "One thing you cannot seem to shift no matter how much you understand it." },
        { kind: "p", text: "WhatsApp access throughout." },
        { kind: "p", text: "Not by only talking about it. By working with the body." },
        { kind: "p", text: "This is for the man who knows what is wrong and wants it handled." },
        { kind: "link", text: "Explore the Intensive →", href: "https://feelfullyyou.com/the-2-month-intensive" },
        { kind: "quote", text: "The Beginning: The Ultimate Touch Reset" },
        { kind: "image", src: "/unspoken-distance/the-beginning-touch-reset.png", alt: "The Beginning: The Ultimate Touch Reset" },
        { kind: "p", text: "Everything in this guide gives you understanding." },
        { kind: "p", text: "The Beginning: The Ultimate Touch Reset gives you eight weeks of embodied experience." },
        { kind: "p", text: "Understanding changes how you think." },
        { kind: "p", text: "Embodied experience changes what your body knows." },
        { kind: "p", text: "Both matter. They are not the same thing.", emphasis: "accent" },
        { kind: "quote", text: "What The Beginning Is" },
        { kind: "p", text: "The Beginning is an eight-week programme for couples who are ready to stop understanding the distance and start closing it." },
        { kind: "p", text: "I split you up. That is deliberate. Each of you builds individual capacity before you bring it into contact with each other." },
        {
          kind: "step",
          label: "What's Inside",
          lines: [
            { text: "Individual Portal Access: built specifically for him and for her, different content, different pace, same direction." },
            { text: "Private 1:1 Calls With Each of You: so each of you get exactly what your body needs." },
            { text: "Couple Call: you bring what you have each built into shared space." },
            { text: "Private WhatsApp or Telegram Access: direct access to me once a week. Real support, for each of you separately." },
            { text: "Touch Dates, Week by Week: structured, building in depth and complexity. Not prescribed. Guided." },
            { text: "A Bespoke Closing Experience: a thirty-minute guided experience recorded specifically for the two of you, to follow together, again and again." },
          ],
        },
        { kind: "p", text: "This is not a course you watch." },
        { kind: "p", text: "It is an experience you have." },
        { kind: "quote", text: "What Becomes Possible" },
        { kind: "p", text: "I have watched couples who had not touched each other with desire in years rediscover each other in this programme." },
        { kind: "p", text: "I have watched men who came in certain the pattern was their wife realise, gently, that the first shift was in them." },
        { kind: "p", text: "I have watched women who had spent years behind glass, present but not fully there, find their way back into their own bodies." },
        { kind: "quote", text: "“The work is quiet. It is not dramatic. It goes into places that most modalities never reach.”" },
        { kind: "p", text: "If you are ready to stop reading about this and start feeling it, this is where that happens." },
        { kind: "p", text: "This is not a course you watch. It is an experience you have.", emphasis: "accent" },
        { kind: "link", text: "Explore The Beginning →", href: "https://feelfullyyou.com/thebeginning" },
      ],
    },
  ],
};
